CREATE TABLE "GCG_3882_ROUTER_SNAPSHOT"(
 "TERMINAL" VARCHAR(3) NOT NULL ,
 "ROUTER" VARCHAR(20) NOT NULL ,
 "SEQ" VARCHAR(6) NOT NULL ,
 "LMO" VARCHAR(1),
 "RUNTIME" NUMERIC(12,4),
 "SETUP" NUMERIC(12,4),
 "QTY" NUMERIC(12,4),
 "RATE" NUMERIC(12,4),
 "VENDOR" VARCHAR(6),
 "PART" VARCHAR(20),
 "WORKCENTER" VARCHAR(50),
 "OUTSIDE" VARCHAR(50),
 PRIMARY KEY ("TERMINAL", "ROUTER", "SEQ"));
